spring:
  data:
    mongodb:
      host: 127.0.0.1
      database: blog
  freemarker:
    templateLoaderPath: classpath:/templates/freemarker/
  thymeleaf:
    prefix: classpath:/templates/thymeleaf/
    cache: false